### ISSUE TITLE
[java.lang.UnsatisfiedLinkError][Android] No implementation found for boolean com.microsoft.applications.events.PrivacyGuard.isInitialized() 

### ISSUE THREAD

**Issue by Manvi-Agrawal-Microsoft** [microsoft/cpp_client_telemetry#1032] opened 2022-07-05 07:19 UTC
### Scenario.
  Facing an issue in upgrading one-ds sdk version to [v3.6.69](https://github.com/microsoft/cpp_client_telemetry/releases/tag/v3.6.69), due to the below crash.
  
 Crash also happening in in one-ds sdk version [v3.5.321](https://github.com/microsoft/cpp_client_telemetry/releases/tag/v3.5.321) if local AAR is being used. This is the oneds sdk version that teams uses currently and we do not face any issue.

**Steps taken to build local aar**
    - Hardcoded ndkVersion to  21.1.6352462/ 21.3.6528147 in lib/android_lib/build.gradle
    - Built maesdk aar using "gradle assemble" and "gradle :maesdk:assemble"
    
**Repro steps:**
    1. Login with above test account. teamsauto94@MSTEAMSMOBILE.onmicrosoft.com/Abcd_1234
    2. Kill and relaunch the app. The app crashes.
  
### Crash
⁠Java_com_microsoft_applications_events_PrivacyGuard_isInitialized and Java_com_microsoft_applications_events_PrivacyGuard_isInitialized__)
2022-06-30 17:10:06.042 20149-7466/com.microsoft.skype.teams.dev E/AndroidRuntime: FATAL EXCEPTION: Pool-Telemetry-Thread-2
Process: com.microsoft.skype.teams.dev, PID: 20149
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.microsoft.applications.events.PrivacyGuard.isInitialized() (tried Java_com_microsoft_applications_events_PrivacyGuard_isInitialized and Java_com_microsoft_applications_events_PrivacyGuard_isInitialized__)
at com.microsoft.applications.events.PrivacyGuard.isInitialized(Native Method)
at com.microsoft.teams.telemetry.logger.OneDSLogger.initializeAndRegisterPrivacyGuard(OneDSLogger.java:565)
at com.microsoft.teams.telemetry.logger.OneDSLogger.initOneDSLoggerForMultiCloud(OneDSLogger.java:540)
at com.microsoft.teams.telemetry.logger.OneDSLogger.lambda$new0  0com-microsoft-teams-telemetry-logger-OneDSLogger(OneDSLogger.java:120)
at com.microsoft.teams.telemetry.logger.OneDSLogger$$ExternalSyntheticLambda14.run(Unknown Source:8)

### Environment: SDK version, platform, OS version, compiler type, etc.
- NDK version: 21.1.6352462(version mentioned in oneDs gradle), 21.3.6528147(ndk version used by teams)
- Platform: Android
- Describe the focus area: transmission controls, offline storage, backend routing controls, reliability, performance, etc.
  N/A
- **Additional context:** 
   [Android section](https://github.com/microsoft/cpp_client_telemetry/blob/main/docs/cpp-start-android.md) of one-ds repo mentions that we should "build the SDK using the same versions of the Android SDK, NDK, and build tooling as our existing app." Tried that as well. Getting the below error while building oneds repo.
   ```
    Build command failed.
   Error while executing process /Users/manviagrawal/Library/Android/sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C /Users/manviagrawal/AndroidStudioProjects/cpp_client_telemetry/lib/android_build/app/.cxx/Debug/122k3w1c/arm64-v8a native-lib}
  ninja: Entering directory `/Users/manviagrawal/AndroidStudioProjects/cpp_client_telemetry/lib/android_build/app/.cxx/Debug/122k3w1c/arm64-v8a'

   ninja: error: '/Users/manviagrawal/AndroidStudioProjects/cpp_client_telemetry/lib/android_build/maesdk/build/intermediates/cmake/debug/obj/arm64-v8a/libmaesdk.so', needed by '/Users/manviagrawal/AndroidStudioProjects/cpp_client_telemetry/lib/android_build/app/build/intermediates/cxx/Debug/122k3w1c/obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it
   ```

   Here is Teams android tooling:
   - Gradle: 7.1.3
   - `distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-bin.zip` in gradle-wrapper.properties
   - Build Tools: 30.0.3
   - compileSdkVersion  = 31
   - minSdkVersion  = 24
   - targetSdkVersion = 30
   - ndkVersion           = "21.3.6528147"

**Comment by lalitb** [comment] 2022-07-05 18:32
> java.lang.UnsatisfiedLinkError: No implementation found for boolean com.microsoft.applications.events.PrivacyGuard.isInitialized() (tried Java_com_microsoft_applications_events_PrivacyGuard_isInitialized and Java_com_microsoft_applications_events_PrivacyGuard_isInitialized__)

This would generally happen if maesdk is not build incorporating privacy guard module, and we are trying to use that module in java application.

**Comment by lalitb** [comment] 2022-07-07 23:48
@Manvi-Agrawal-Microsoft - Is it good to close the issue?

**Comment by lalitb** [comment] 2022-07-08 17:14
Closing as discussed. Please reopen if the issue is still there.

**Closed by lalitb** 2022-07-08 17:14 UTC
Labels: question
