### ISSUE TITLE
CFG_STR_COLLECTOR_URL has no effect, events still get sent to default endpoint

### ISSUE THREAD

**Issue by theta3** [microsoft/cpp_client_telemetry#825] opened 2021-04-08 20:32 UTC
**Describe your environment.** git branch outlookmobile/droid, commit SHA 0963fcbc491d7e1a8a20e4dc4a0976ee8a505abf

**Steps to reproduce.**
`````
ILogConfiguration logConfiguration = LogManager.getLogConfigurationCopy();
...
logConfiguration.set(LogConfigurationKey.CFG_STR_COLLECTOR_URL, "https://url/");
ILogManager logManager = LogManagerProvider.createLogManager(logConfiguration);
ILogger logger = logManager.getLogger(tenantId /* token */, source /* source */, "" /* scope */);
`````

**What is the expected behavior?**
Events sent to custom endpoint

**What is the actual behavior?**
Events still sent to default endpoint

**Additional context.**
None

**Comment by theta3** [comment] 2021-04-08 20:33
@larvacea Could you please take a quick look?

**Comment by larvacea** [comment] 2021-04-08 21:00
You may need to set CFG_STR_FACTORY_NAME as well.

This is part of the unit test suite for Android:
```
cpp_client_telemetry/lib/android_build/app/src/androidTest/java/com/microsoft/applications/events/maesdktest/LogManagerDDVUnitTest.java
```

**Comment by larvacea** [comment] 2021-04-08 21:09
In the test example, I configure a custom database path as well.

- The custom-endpoint log manager will use its own private database when it persists events for later upload.
- It will pull events from this database when  uploading to the custom endpoint.
- It won't pull events intended for some other endpoint and upload them to its endpoint, nor will other log managers pull events from this database and upload them to their collector URL.

**Comment by theta3** [comment] 2021-04-08 23:59
> In the test example, I configure a custom database path as well.
> 
> * The custom-endpoint log manager will use its own private database when it persists events for later upload.
> * It will pull events from this database when  uploading to the custom endpoint.
> * It won't pull events intended for some other endpoint and upload them to its endpoint, nor will other log managers pull events from this database and upload them to their collector URL.

@larvacea is that the purpose of CFG_STR_CACHE_FILE_PATH?

**Comment by larvacea** [comment] 2021-04-09 18:49
Yes: CFG_STR_CACHE_FILE_PATH names the database files that the LogManager instance will use. Since the database does not record the collector URL associated with an event, if you want to have multiple endpoints you will need multiple databases, one for each LogManager.

**Comment by theta3** [comment] 2021-04-09 19:00
The developer is still not seeing the events sent to the custom endpoint. Here is what I added:
`````
URL endpointUrl = new URL(endpoint);
String factoryName = endpointUrl.getHost();
logConfiguration.set(LogConfigurationKey.CFG_STR_FACTORY_NAME, factoryName);
logConfiguration.set(LogConfigurationKey.CFG_STR_CACHE_FILE_PATH, factoryName);
`````
Looks like iOS sets `CFG_STR_FACTORY_HOST`. What's the difference between it and `CFG_STR_FACTORY_NAME` ?

**Comment by theta3** [comment] 2021-04-16 21:40
@larvacea I finally got Fiddler to work and I can't see the custom endpointUrl got hit. I can see the custom cache file got created in the temp folder so some configs were picked up. I only see requests to `self.events.data.microsoft.com/OneCollector/1.0/`. How do I debug this further?

`````
 URL endpointUrl = new URL(endpoint);
factoryName = endpointUrl.getHost();
 logConfiguration.set(LogConfigurationKey.CFG_STR_COLLECTOR_URL, endpoint);
logConfiguration.set(LogConfigurationKey.CFG_STR_FACTORY_NAME, factoryName);
logConfiguration.set(LogConfigurationKey.CFG_STR_FACTORY_HOST, factoryName);
logConfiguration.set(LogConfigurationKey.CFG_STR_CACHE_FILE_PATH, factoryName);
`````

**Comment by larvacea** [comment] 2021-04-20 20:02
Let me try that out on my end; I'll let you know the debugging steps, to prep you for debugging the Inevitable Next Time.

**Comment by theta3** [comment] 2021-04-26 15:49
@larvacea any good news?

**Comment by larvacea** [comment] 2021-10-04 21:52
I can take another look at my Java tests that are supposed to check this behavior.

The intended effect is that a log manager instance configured with its own database path and its own endpoint URL should log its events (and only its events) to that configured URL. In C++ land, that was working when last I looked at it, and unless something is horribly broken in the Java wrappers, the wrappers should provide a clean path into that C++ behavior and let you configure a logManager specific to that custom URL.

**Comment by lalitb** [comment] 2022-06-30 06:57
@theta3 Just wondering if the issue is still valid, as there are users using this configuration parameter to set up multiple log managers with different endpoint url. So should be working in your setup too.

**Comment by aamittal1989** [comment] 2022-08-16 05:03
I tried the same scenario (there are users using this configuration parameter to set up multiple log managers with different endpoint url.) in Teams Android with the OneDS latest version, its working fine for me.

**Comment by lalitb** [comment] 2022-08-18 03:52
Thanks for confirming @aamittal1989 .

@theta3 - Closing this as it is known working. Please reopen it if you see the issue with latest version.

**Closed by lalitb** 2022-08-18 03:52 UTC
Labels: bug, Android, iOS
